// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package passenger_feeback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feedback) Reset()         { *m = Feedback{} }
func (m *Feedback) String() string { return proto.CompactTextString(m) }
func (*Feedback) ProtoMessage()    {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feedback.Unmarshal(m, b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
}
func (m *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(m, src)
}
func (m *Feedback) XXX_Size() int {
	return xxx_messageInfo_Feedback.Size(m)
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *Feedback) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

func (m *Feedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type AddFeedbackRequest struct {
	Feedback             *Feedback `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddFeedbackRequest) Reset()         { *m = AddFeedbackRequest{} }
func (m *AddFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*AddFeedbackRequest) ProtoMessage()    {}
func (*AddFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *AddFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFeedbackRequest.Unmarshal(m, b)
}
func (m *AddFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *AddFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFeedbackRequest.Merge(m, src)
}
func (m *AddFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_AddFeedbackRequest.Size(m)
}
func (m *AddFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFeedbackRequest proto.InternalMessageInfo

func (m *AddFeedbackRequest) GetFeedback() *Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type GetByPassengerIdRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByPassengerIdRequest) Reset()         { *m = GetByPassengerIdRequest{} }
func (m *GetByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByPassengerIdRequest) ProtoMessage()    {}
func (*GetByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPassengerIdRequest.Unmarshal(m, b)
}
func (m *GetByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *GetByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPassengerIdRequest.Merge(m, src)
}
func (m *GetByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByPassengerIdRequest.Size(m)
}
func (m *GetByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPassengerIdRequest proto.InternalMessageInfo

func (m *GetByPassengerIdRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type GetByBookingCodeRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByBookingCodeRequest) Reset()         { *m = GetByBookingCodeRequest{} }
func (m *GetByBookingCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetByBookingCodeRequest) ProtoMessage()    {}
func (*GetByBookingCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetByBookingCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBookingCodeRequest.Unmarshal(m, b)
}
func (m *GetByBookingCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBookingCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetByBookingCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBookingCodeRequest.Merge(m, src)
}
func (m *GetByBookingCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetByBookingCodeRequest.Size(m)
}
func (m *GetByBookingCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBookingCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBookingCodeRequest proto.InternalMessageInfo

func (m *GetByBookingCodeRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type DeleteByPassengerIdRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByPassengerIdRequest) Reset()         { *m = DeleteByPassengerIdRequest{} }
func (m *DeleteByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteByPassengerIdRequest) ProtoMessage()    {}
func (*DeleteByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByPassengerIdRequest.Unmarshal(m, b)
}
func (m *DeleteByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByPassengerIdRequest.Merge(m, src)
}
func (m *DeleteByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteByPassengerIdRequest.Size(m)
}
func (m *DeleteByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByPassengerIdRequest proto.InternalMessageInfo

func (m *DeleteByPassengerIdRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type FeedbackResponse struct {
	Feedback             *Feedback `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Success              bool      `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FeedbackResponse) Reset()         { *m = FeedbackResponse{} }
func (m *FeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*FeedbackResponse) ProtoMessage()    {}
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *FeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedbackResponse.Unmarshal(m, b)
}
func (m *FeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedbackResponse.Marshal(b, m, deterministic)
}
func (m *FeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedbackResponse.Merge(m, src)
}
func (m *FeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_FeedbackResponse.Size(m)
}
func (m *FeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedbackResponse proto.InternalMessageInfo

func (m *FeedbackResponse) GetFeedback() *Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

func (m *FeedbackResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type FeedbackListResponse struct {
	FeedbackList         []*Feedback `protobuf:"bytes,1,rep,name=feedbackList,proto3" json:"feedbackList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FeedbackListResponse) Reset()         { *m = FeedbackListResponse{} }
func (m *FeedbackListResponse) String() string { return proto.CompactTextString(m) }
func (*FeedbackListResponse) ProtoMessage()    {}
func (*FeedbackListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *FeedbackListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedbackListResponse.Unmarshal(m, b)
}
func (m *FeedbackListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedbackListResponse.Marshal(b, m, deterministic)
}
func (m *FeedbackListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedbackListResponse.Merge(m, src)
}
func (m *FeedbackListResponse) XXX_Size() int {
	return xxx_messageInfo_FeedbackListResponse.Size(m)
}
func (m *FeedbackListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedbackListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedbackListResponse proto.InternalMessageInfo

func (m *FeedbackListResponse) GetFeedbackList() []*Feedback {
	if m != nil {
		return m.FeedbackList
	}
	return nil
}

func init() {
	proto.RegisterType((*Feedback)(nil), "passenger_feeback.Feedback")
	proto.RegisterType((*AddFeedbackRequest)(nil), "passenger_feeback.AddFeedbackRequest")
	proto.RegisterType((*GetByPassengerIdRequest)(nil), "passenger_feeback.GetByPassengerIdRequest")
	proto.RegisterType((*GetByBookingCodeRequest)(nil), "passenger_feeback.GetByBookingCodeRequest")
	proto.RegisterType((*DeleteByPassengerIdRequest)(nil), "passenger_feeback.DeleteByPassengerIdRequest")
	proto.RegisterType((*FeedbackResponse)(nil), "passenger_feeback.FeedbackResponse")
	proto.RegisterType((*FeedbackListResponse)(nil), "passenger_feeback.FeedbackListResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xc9, 0xbf, 0xfc, 0xb5, 0x4e, 0x3d, 0xd4, 0x55, 0x30, 0xc4, 0x4b, 0x88, 0x88, 0x45,
	0xb0, 0x87, 0x7a, 0xf0, 0x20, 0x28, 0xc6, 0xa2, 0x08, 0x16, 0x24, 0x17, 0xf1, 0x24, 0x79, 0x99,
	0x84, 0x58, 0xcd, 0xc6, 0xec, 0xe6, 0xe0, 0x77, 0xf2, 0x43, 0x4a, 0x42, 0x77, 0xb3, 0x6d, 0x5e,
	0x2c, 0xbd, 0x65, 0x27, 0xfb, 0x3c, 0xbf, 0xc9, 0xcc, 0x13, 0x80, 0x9c, 0x61, 0x36, 0x4e, 0x33,
	0xca, 0x29, 0xd9, 0x4b, 0x5d, 0xc6, 0x30, 0x89, 0x30, 0x7b, 0x0b, 0x11, 0x3d, 0xd7, 0x9f, 0x5b,
	0xef, 0xd0, 0xbf, 0x47, 0x0c, 0x8a, 0x67, 0x62, 0xc2, 0xc0, 0xa3, 0x74, 0x1e, 0x27, 0xd1, 0x1d,
	0x0d, 0x50, 0xd7, 0x4c, 0x6d, 0xb4, 0xe3, 0xa8, 0xa5, 0xe2, 0x86, 0xb4, 0x78, 0x9c, 0xea, 0xff,
	0x4c, 0x6d, 0xf4, 0xdf, 0x51, 0x4b, 0xc4, 0x80, 0x7e, 0xb8, 0xf0, 0xd3, 0x7b, 0xa5, 0x81, 0x3c,
	0x5b, 0x33, 0x20, 0xb7, 0x41, 0x20, 0x70, 0x0e, 0x7e, 0xe5, 0xc8, 0x38, 0xb9, 0x54, 0x14, 0x05,
	0x72, 0x30, 0x39, 0x1a, 0xd7, 0xfa, 0x1c, 0x4b, 0x55, 0x65, 0x77, 0x05, 0x87, 0x0f, 0xc8, 0xed,
	0xef, 0x67, 0x89, 0x0f, 0x84, 0xe7, 0x4a, 0x9f, 0x5a, 0xad, 0x4f, 0x29, 0xb6, 0xab, 0xaf, 0x53,
	0xc4, 0xdd, 0x63, 0xb0, 0xae, 0xc1, 0x98, 0xe2, 0x07, 0x72, 0xdc, 0x10, 0x8e, 0x30, 0xac, 0xa6,
	0xc0, 0x52, 0x9a, 0x30, 0xdc, 0x78, 0x0c, 0x44, 0x87, 0x6d, 0x96, 0xfb, 0x3e, 0x32, 0x56, 0xee,
	0xa3, 0xef, 0x88, 0xa3, 0xf5, 0x02, 0x07, 0xe2, 0xfe, 0x53, 0xcc, 0xb8, 0x44, 0xdd, 0xc0, 0x6e,
	0xa8, 0xd4, 0x75, 0xcd, 0xec, 0xfd, 0x85, 0x5b, 0x12, 0x4c, 0x7e, 0x7a, 0x40, 0xc4, 0xab, 0x99,
	0x9b, 0xb8, 0x11, 0x7e, 0x62, 0xc2, 0xc9, 0x2b, 0x0c, 0x16, 0xfb, 0xb5, 0x8b, 0xc6, 0x4e, 0x1a,
	0x0c, 0xeb, 0xfb, 0x37, 0x8e, 0xbb, 0xb8, 0xa2, 0xe5, 0x08, 0x86, 0xab, 0xbb, 0x26, 0x67, 0x0d,
	0xc2, 0x96, 0x40, 0x18, 0xa7, 0x1d, 0x90, 0xa5, 0xd9, 0x08, 0x90, 0x92, 0x8b, 0x76, 0x50, 0x3d,
	0x3c, 0xeb, 0x83, 0x62, 0xd8, 0x6f, 0xc8, 0x10, 0x39, 0x6f, 0xd0, 0xb7, 0x67, 0x6d, 0xad, 0xe1,
	0x79, 0x5b, 0xe5, 0xdf, 0x7f, 0xf1, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x40, 0x65, 0x53, 0x6a, 0x0b,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedbackManagementClient is the client API for FeedbackManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedbackManagementClient interface {
	AddFeedBack(ctx context.Context, in *AddFeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
	GetByPassengerId(ctx context.Context, in *GetByPassengerIdRequest, opts ...grpc.CallOption) (*FeedbackListResponse, error)
	GetByBookingCode(ctx context.Context, in *GetByBookingCodeRequest, opts ...grpc.CallOption) (*FeedbackListResponse, error)
	DeleteByPassengerId(ctx context.Context, in *DeleteByPassengerIdRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
}

type feedbackManagementClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackManagementClient(cc *grpc.ClientConn) FeedbackManagementClient {
	return &feedbackManagementClient{cc}
}

func (c *feedbackManagementClient) AddFeedBack(ctx context.Context, in *AddFeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := c.cc.Invoke(ctx, "/passenger_feeback.FeedbackManagement/AddFeedBack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackManagementClient) GetByPassengerId(ctx context.Context, in *GetByPassengerIdRequest, opts ...grpc.CallOption) (*FeedbackListResponse, error) {
	out := new(FeedbackListResponse)
	err := c.cc.Invoke(ctx, "/passenger_feeback.FeedbackManagement/GetByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackManagementClient) GetByBookingCode(ctx context.Context, in *GetByBookingCodeRequest, opts ...grpc.CallOption) (*FeedbackListResponse, error) {
	out := new(FeedbackListResponse)
	err := c.cc.Invoke(ctx, "/passenger_feeback.FeedbackManagement/GetByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackManagementClient) DeleteByPassengerId(ctx context.Context, in *DeleteByPassengerIdRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := c.cc.Invoke(ctx, "/passenger_feeback.FeedbackManagement/DeleteByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackManagementServer is the server API for FeedbackManagement service.
type FeedbackManagementServer interface {
	AddFeedBack(context.Context, *AddFeedbackRequest) (*FeedbackResponse, error)
	GetByPassengerId(context.Context, *GetByPassengerIdRequest) (*FeedbackListResponse, error)
	GetByBookingCode(context.Context, *GetByBookingCodeRequest) (*FeedbackListResponse, error)
	DeleteByPassengerId(context.Context, *DeleteByPassengerIdRequest) (*FeedbackResponse, error)
}

// UnimplementedFeedbackManagementServer can be embedded to have forward compatible implementations.
type UnimplementedFeedbackManagementServer struct {
}

func (*UnimplementedFeedbackManagementServer) AddFeedBack(ctx context.Context, req *AddFeedbackRequest) (*FeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFeedBack not implemented")
}
func (*UnimplementedFeedbackManagementServer) GetByPassengerId(ctx context.Context, req *GetByPassengerIdRequest) (*FeedbackListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByPassengerId not implemented")
}
func (*UnimplementedFeedbackManagementServer) GetByBookingCode(ctx context.Context, req *GetByBookingCodeRequest) (*FeedbackListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByBookingCode not implemented")
}
func (*UnimplementedFeedbackManagementServer) DeleteByPassengerId(ctx context.Context, req *DeleteByPassengerIdRequest) (*FeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByPassengerId not implemented")
}

func RegisterFeedbackManagementServer(s *grpc.Server, srv FeedbackManagementServer) {
	s.RegisterService(&_FeedbackManagement_serviceDesc, srv)
}

func _FeedbackManagement_AddFeedBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackManagementServer).AddFeedBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passenger_feeback.FeedbackManagement/AddFeedBack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackManagementServer).AddFeedBack(ctx, req.(*AddFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackManagement_GetByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackManagementServer).GetByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passenger_feeback.FeedbackManagement/GetByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackManagementServer).GetByPassengerId(ctx, req.(*GetByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackManagement_GetByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByBookingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackManagementServer).GetByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passenger_feeback.FeedbackManagement/GetByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackManagementServer).GetByBookingCode(ctx, req.(*GetByBookingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackManagement_DeleteByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackManagementServer).DeleteByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passenger_feeback.FeedbackManagement/DeleteByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackManagementServer).DeleteByPassengerId(ctx, req.(*DeleteByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedbackManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "passenger_feeback.FeedbackManagement",
	HandlerType: (*FeedbackManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFeedBack",
			Handler:    _FeedbackManagement_AddFeedBack_Handler,
		},
		{
			MethodName: "GetByPassengerId",
			Handler:    _FeedbackManagement_GetByPassengerId_Handler,
		},
		{
			MethodName: "GetByBookingCode",
			Handler:    _FeedbackManagement_GetByBookingCode_Handler,
		},
		{
			MethodName: "DeleteByPassengerId",
			Handler:    _FeedbackManagement_DeleteByPassengerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
